config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'books#index', as: :authenticated_root, "user_id"=>true
  end

  root to: 'pages#landing'

  resources :users, only: [:show, :update] do
    resources :books, only: [:index], name_prefix: "user_"
  end

  resources :books, only: [:show, :new, :create, :update, :destroy] do
    resources :chapters, only: [:create, :show, :update, :destroy], name_prefix: "book_"
    resources :characters, only: [:create, :index, :show, :update, :destroy], name_prefix: "book_"
    resources :places, only: [:create, :index, :show, :destroy], name_prefix: "book_"
  end

  resources :users, only: :show

  resources :books, only: :index

  resources :relationships, only: [:create, :destroy]

  resources :reactions, only: [:create, :update]

  get "modal_chapters" => 'books#modal_chapters', as: 'modal_chapters'

  get "books" => "books#index",  as: :user_root_path

  get "books/:book_id/statistics" => "books#statistics", as: :book_statistics

  get "books/:book_id/settings" => "books#settings", as: :book_settings

  get "books/:book_id/chapters/:chapter_id/refresh_wordcount" => "chapters#refresh_wordcount", as: :refresh_wordcount

  get "books/:book_id/download" => "books#download", as: :download_book, format: 'docx'

  get "/rankings" => "pages#rankings", as: :rankings

  get "/privacy" => "pages#privacy_policy"

  get "/tos" => "pages#tos"

  get "/cgu" => "pages#cgu", as: :cgu

  get "/mentions_legales" => "pages#mentions_legales", as: :mentions_legales

  mount Attachinary::Engine => "/attachinary"

end

app/views/shared/_cards.html.erb
<div class="card card--add card--book">
  <div class="card__upper-content">
    <div class="card__title-section card__title--add">Ajouter un livre</div>
  </div>
  <a class="card__link card__link--add" data-toggle="modal" href="#exampleModal" data-target="#exampleModal" id="add-book-btn"></a>
</div>
<% @books.each do |book| %>
  <div class="card card--book">
    <div class="card__upper-content">
      <div class="card__title-section">
        <h3 class="card__title"><%= book.title %></h3>
      </div>
    </div>
    <div class="card__lower-content">
      <div class="card__book-chapters"><%= book.chapters.count %> chapitres</div>
      <div class="card__wordcount"><%= book.wordcount %> mots</div>
    </div>
    <%= link_to "", book_path(book), class:"card__link" %>
 </div>
<% end %>

app/views/shared/_dashboard_sidebar.html.erb
<div class="sidebar">
  <div class="sidebar-buttons">
    <a class="sidebar-item <%= "sidebar-item--active" if defined?(chapters) %>" href="<%= book_path(@book) %>">
      Chapitres
    </a>
    <a class="sidebar-item <%= "sidebar-item--active" if defined?(characters) %>" href="<%= book_characters_path(@book) %>">
      Personnages
    </a>
    <a class="sidebar-item <%= "sidebar-item--active" if defined?(places) %>" href="<%= book_places_path(@book) %>">
      Lieux
    </a>
  </div>
    <a href="<%= download_book_path(@book) %>" class="sidebar-item sidebar-cta hidden-xs hidden-sm">
        <i class="fa fa-cloud-download" aria-hidden="true"></i>
      Téléchargez votre livre
    </a>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="landing-footer">
  <ul class="landing-footer-list">
    <li class="underlined-anchor"><a href="http://simonguillor.it" target="_blank">simonguillor.it</a></li>
    <li class="underlined-anchor"><%= link_to "CGU", cgu_path %></li>
    <li class="underlined-anchor"><%= link_to "Mentions Légales", mentions_legales_path %></li>
  </ul>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon
  <% if defined?(landing) %>
    <%= "navbar-wagon--landing" %>
  <% elsif defined?(profile) %>
    <%= "navbar-wagon--profile" %>
  <% end %>
">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    inkip.it
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

    <% if current_user.admin %>

      <div class="navbar-wagon-item underlined-anchor">
        <%= link_to admin_root_path do %>
           <%= t(".profile", default: "Admin") %>
        <% end %>
      </div>
    <% end %>

    <div class="navbar-wagon-item underlined-anchor">
      <%= link_to user_books_path(current_user), user: true do %>
         <%= t(".profile", default: "Dashboard", class: "hidden-xs") %>
      <% end %>
    </div>

    <div class="navbar-wagon-item underlined-anchor">
      <%= link_to books_path(filter: "last") do %>
         <%= t(".profile", default: "Communauté", class: "hidden-xs") %>
      <% end %>
    </div>

    <div class="navbar-wagon-item underlined-anchor">
      <%= link_to destroy_user_session_path, method: :delete do %>
        <%= t(".sign_out", default: "Déconnexion") %>
      <% end %>
    </div>

    <% else %>

    <div class="navbar-wagon-item underlined-anchor">
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    </div>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-burger hidden-md hidden-lg">
    <div class="dropdown">
      <button class="hamburger hamburger--spin" type="button" data-toggle="dropdown">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
        </span>
      </button>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
          <% if current_user.admin %>
            <li>
              <%= link_to admin_root_path do %>
                 <%= t(".profile", default: "Admin") %>
              <% end %>
            </li>
          <% end %>
          <li>
            <%= link_to user_books_path(current_user) do %>
               <%= t(".profile", default: "Dashboard") %>
            <% end %>
          </li>
          <li>
            <%= link_to books_path(filter: "last") do %>
               <%= t(".profile", default: "Communauté") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <%= t(".sign_out", default: "Déconnexion") %>
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_dashboard.html.erb
<div class="navbar-book-dashboard">
  <div class="navbar-book-title hidden-xs hidden-sm">
    <% if defined?(character_sheet) %>
      <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
      <a href="<%= book_characters_path(@book) %>">
        <%= "Liste des personnages" %>
      </a>
    <% else %>
      <%= @book.title %>
    <% end %>
  </div>
  <div class="navbar-book-dashboard-content">
    <ul class="navbar-book-list">
    <li class="navbar-item <%= "navbar-item--active" if defined?(dashboard) %>"><a href="<%= book_path(@book) %>">Écrire</a></li>
    <li class="navbar-item <%= "navbar-item--active" if defined?(statistics) %>""><a href="<%= book_statistics_path(@book) %>">Analyser</a></li>
    <li class="navbar-item <%= "navbar-item--active" if defined?(settings) %>"><a href="<%= book_settings_path(@book)%>">Configurer</a></li>
    </ul>
  </div>
</div>

app/views/shared/_pagination.html.erb
<div class="pagination-container">
  <%== pagy_nav(@pagy) if @filter == "last" %>
</div>