config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'books#index', as: :authenticated_root, "user_id"=>true
  end

  root to: 'pages#landing'

  resources :users, only: [:show, :update] do
    resources :books, only: [:index], name_prefix: "user_"
  end

  resources :books, only: [:show, :new, :create, :update, :destroy] do
    resources :chapters, only: [:create, :show, :update, :destroy], name_prefix: "book_"
    resources :characters, only: [:create, :index, :show, :update, :destroy], name_prefix: "book_"
    resources :places, only: [:create, :index, :show, :destroy], name_prefix: "book_"
  end

  resources :users, only: :show

  resources :books, only: :index

  resources :relationships, only: [:create, :destroy]

  resources :reactions, only: [:create, :update]

  get "modal_chapters" => 'books#modal_chapters', as: 'modal_chapters'

  get "books" => "books#index",  as: :user_root_path

  get "books/:book_id/statistics" => "books#statistics", as: :book_statistics

  get "books/:book_id/settings" => "books#settings", as: :book_settings

  get "books/:book_id/chapters/:chapter_id/refresh_wordcount" => "chapters#refresh_wordcount", as: :refresh_wordcount

  get "books/:book_id/download" => "books#download", as: :download_book, format: 'docx'

  get "/rankings" => "pages#rankings", as: :rankings

  get "/privacy" => "pages#privacy_policy"

  get "/tos" => "pages#tos"

  get "/cgu" => "pages#cgu", as: :cgu

  get "/mentions_legales" => "pages#mentions_legales", as: :mentions_legales

  mount Attachinary::Engine => "/attachinary"

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :chapters, dependent: :destroy
  has_many :characters, dependent: :destroy
  has_many :places, dependent: :destroy
  has_many :streaks, dependent: :destroy
  has_many :daily_word_counts, dependent: :destroy
  has_many :reactions, through: :chapters

  scope :find_lazy, ->(id) { where(id: id) }

  validate do |book|
    book.errors.add(:base, "Ajoutez un titre à votre livre ! Vous pourrez le modifier par la suite.") if book.title.blank?
  end

  after_create :init

  def init
    self.max_streaks ||= 0
    self.current_streaks ||= 0
    self.max_daily_wordcount ||= 0
  end

  def signs
    signs = 0
    chapters.each do |chapter|
      signs += chapter.signs unless chapter.content.nil?
    end
    signs
  end

  def wordcount
    words = 0
    chapters.each do |chapter|
      words += chapter.wordcount unless chapter.content.nil?
    end
    words
  end

  def word_goal_ratio
    if word_goal != nil && word_goal > 0
      wordcount.to_f / word_goal
    else
      0
    end
  end

  def average_daily_wordcount
    wordcount / age_in_days
  end

  def age_in_days
    ((Time.current - created_at) / (60*60*24)).floor
  end

  def words_per_session
    dwc_all = daily_word_counts.sort_by { |obj| obj.wordcount }.reverse!
    dwc_all.shift

    dwc_wordcount = 0

    dwc_all.each do |dwc|
      dwc_wordcount += dwc.wordcount
    end

    unless chapters.empty? || dwc_all.empty?
      words_per_session = dwc_wordcount / dwc_all.count
    else
      words_per_session = 0
    end
  end

  def self.best_max_dwc
    Book.where('max_streaks > 1 & max_daily_wordcount IS NOT NULL').order(max_daily_wordcount: :desc)
  end

  def self.best_average_dwc
    books_average_dwc = []

    Book.where('max_streaks > 1').includes(:daily_word_counts, :chapters).each do |book|
      books_average_dwc << [book, book.words_per_session]
    end

    books_average_dwc_sorted = books_average_dwc.sort {|a, b| b[1] <=> a[1]}
  end

  def self.best_maximum_streaks
    Book.where.not(max_streaks: nil).order(max_streaks: :desc)
  end

  def self.published
    chapters = Chapter.published.sort_by &:updated_at
    chapters.reverse!
    books_ids = chapters.pluck(:book_id)
    Book.find_lazy(books_ids)
  end

  def published?
    chapters.any? {|chapter| chapter.published == true}
  end

  def published_chapters
    Chapter.where(published: true, book: self).order(:created_at)
  end

  def inks
    published_chapters.includes(:reactions).sum(&:inks)
  end

  def self.published_popular
    books = Book.published.limit(10)
    books.sort { |x, y| y.inks <=> x.inks }
  end

  def is_completed?
    word_goal_ratio >= 1
  end

  def self.authored_by_followers_of(user)
    following = user.following
    books = []

    Book.includes(:user).where(user: following).each do |book|
      books << book if book.published?
    end
    books
  end

  def last_month_daily_word_counts
    daily_word_counts.order('created_at').last(30)
  end

  def last_year_daily_word_counts
    daily_word_counts.order('created_at').last(365)
  end

  def daily_word_counts_info
    dwc_dates = []
    dwc_values = []
    dwc_total_values = []

    last_month_daily_word_counts.each do |dwc|
      dwc_dates << dwc.created_at.strftime('%d/%m/%Y')
      dwc_values << dwc.wordcount
      dwc_total_values << dwc.total_word_count
    end

    [dwc_dates, dwc_values, dwc_total_values]
  end

  def words_left
    word_goal - wordcount if word_goal
  end

  def daily_word_counts_calendar
    dwc_map = last_year_daily_word_counts.map {|dwc| [dwc.created_at.to_datetime.strftime('%s'), dwc.wordcount]}
    Hash[dwc_map]
  end

  def global_words_per_session
    all_dwc = DailyWordCount.where('wordcount < 10000')
    dwc = last_month_daily_word_counts

    all_dwc_size = 0

    all_dwc.each do |dwc|
      all_dwc_size += dwc.wordcount unless dwc.wordcount.nil? || dwc.wordcount > 10000
    end

    (all_dwc_size / all_dwc.count) unless all_dwc.count == 0
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  include Pagy::Backend

  def index
    @user = current_user
    @book = Book.new

    case params['filter']

    when 'last'
      @pagy, @books = pagy(Book.includes(:user).published, items: 10)
      @filter = 'last'

    when 'popular'
      @books = Book.includes(:user).published_popular
      @filter = 'popular'

      respond_to do |format|
        format.js
      end

    when 'following'
      @books = Book.authored_by_followers_of(@user)
      @filter = 'following'

      respond_to do |format|
        format.js
      end

    else
      @user_library = true
      @books = Book.where(user: current_user).includes(:user).order('updated_at DESC')
      @books_published = @user.published_books
    end
  end

  def show
    @book = Book.find(params[:id])
    authorize @book
    @chapters = @book.chapters.order('created_at')
    @chapter = Chapter.new
    @characters = @book.characters
    @character = Character.new
    @places = @book.places
    @place = Place.new
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    authorize @book

    respond_to do |format|
      if @book.save
        flash[:notice] = "Vous avez ajouté un nouveau livre !"
        format.js {render js: "window.location.href='#{book_path(@book)}'"}
      else
        format.js {render "books/errors"}
      end
    end
  end

  def update
    @book = Book.find(params[:id])
    authorize @book

    if @book.update(book_params)
      redirect_to book_settings_path(@book), alert: "Vous avez modifié votre livre !"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    authorize @book

    redirect_to user_books_path(current_user), alert: "Vous venez d'effacer votre livre :( !"
  end

  def download
    @book = Book.find(params[:book_id])
    authorize @book

    chapters = @book.chapters.order('created_at')

    @book_content = []

    chapters.each do |chapter|
      @book_content << [chapter.title, chapter.content]
    end

    respond_to do |format|
      format.docx do
        render docx: 'download_book', filename: @book.title + ".docx"
      end
    end
  end

  def statistics
    @book = Book.find(params[:book_id])
    authorize @book

    chapters = @book.chapters

    # DWC

    gon.dwc_dates = @book.daily_word_counts_info[0].as_json
    gon.dwc_values = @book.daily_word_counts_info[1].as_json
    gon.dwc_total_values = @book.daily_word_counts_info[2].as_json

    # WORDCOUNT GOAL

    gon.wordcount = @book.wordcount

    if @book.word_goal
      gon.words_left = @book.words_left
    end

    # CAL-HEATMAP

    gon.dwc_calendar = @book.daily_word_counts_calendar

    # WORDS PER SESSION

    @words_per_session = @book.words_per_session

    # GLOBAL WORDS PER SESSION MEAN

    @global_words_per_session = @book.global_words_per_session

    # WORDS PER CHAPTER

    unless chapters.empty?
      @words_per_chapter = (@book.wordcount / chapters.count)
    else
      @words_per_chapter = 0
    end

  end

  def settings
    @book = Book.find(params[:book_id])
    authorize @book

  end

  def modal_chapters
    @book = Book.find(params[:book_id])
    authorize @book

    respond_to do |format|
        format.js
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :word_goal)
  end

end

app/views/books/_card_published_books.html.erb
<% @books.each do |book| %>
  <div class="card card--book card--published-book">
    <div class="small-avatar card__book-avatar" style="background-image: url(<%= book.user.profile_picture_url %>)"></div>
    <div class="card__inks">
      <div class="card__inks-image" style="background-image: url(<%= image_path("inkdrop2.svg") %>)"></div>
      <span><%= book.inks %> inks</span>
    </div>

    <div class="card__upper-content">
      <div class="card__title-section">
        <h3 class="card__title"><%= book.title %></h3>
      </div>
    </div>
    <div class="card__lower-content">
      <div class="card__book-author"><%= book.user.user_name %></div>
      <div class="card__book-chapters"><%= book.published_chapters.count %> chapitres publiés</div>
    </div>
    <%= link_to "", modal_chapters_path(book_id: book.id), remote: true, class:"card__link" %>
  </div>
<% end %>

app/views/books/_download_chapter.docx.erb
<h2><%= chapter[0] %></h2>

<br>
<% chapter[1].split("<br>").each do |string|  %>
<%= ActionView::Base.full_sanitizer.sanitize(string) %>
  <br>
<% end %>

<div class="-page-break"></div>

app/views/books/_navbar_dashboard_community.html.erb
<div class="navbar-book-dashboard">
  <div class="navbar-book-title hidden-xs hidden-sm">

  </div>
  <div class="navbar-book-dashboard-content">
    <ul class="navbar-book-list">
    <li class="navbar-item <%= "navbar-item--active" if current_page?(:controller => 'books', :action => 'index') %>"><a href="<%= books_path(filter: "last") %>">A lire</a></li>
    <li class="navbar-item <%= "navbar-item--active" unless current_page?(:controller => 'books', :action => 'index') %>"><a href="<%= rankings_path %>">Classement</a></li>
    </ul>
  </div>
</div>

app/views/books/_navbar_dashboard_profile.html.erb
<div class="navbar-book-dashboard">
  <div class="navbar-book-title hidden-xs hidden-sm">

  </div>
  <div class="navbar-book-dashboard-content">
    <ul class="navbar-book-list">
    <li class="navbar-item <%= "navbar-item--active" if current_page?(:controller => 'books', :action => 'index') %>"><a href="<%= user_books_path(current_user) %>">Vos Livres</a></li>
    <li class="navbar-item <%= "navbar-item--active" unless current_page?(:controller => 'books', :action => 'index') %>"><a href="<%= user_path(current_user) %>">Profil</a></li>
    </ul>
  </div>
</div>

app/views/books/_sidebar_community.html.erb
<div class="sidebar sidebar--community">
  <div class="sidebar-buttons">
    <h2 class="sidebar-title">Communauté</h2>
    <%= link_to "Dernières publications", books_path(filter: "last"), class: "sidebar-item sidebar-item--rankings sidebar-item--community #{'sidebar-item--active' if params["filter"] == "last"}" , id: 'sidebar-item--last', remote: true %>
    <%= link_to "Les plus populaires", books_path(filter: "popular"), class: "sidebar-item sidebar-item--rankings sidebar-item--community #{'sidebar-item--active' if params["filter"] == "popular"}" , id: 'sidebar-item--popular', remote: true %>
    <%= link_to "Abonnements", books_path(filter: "following"), class: "sidebar-item sidebar-item--rankings sidebar-item--community #{'sidebar-item--your-books sidebar-item--active' if params["filter"] == "following"}" , id: 'sidebar-item--following',  remote: true %>
  </div>
</div>

app/views/books/_sidebar_dashboard.html.erb
<div class="sidebar sidebar--dashboard">
  <div class="sidebar-buttons">
    <h2 class="sidebar-title">Vos livres</h2>
    <a href="" class="sidebar-item sidebar-item--rankings sidebar-item--your-books sidebar-item--active">Tous vos livres</a>
    <a href="" class="sidebar-item sidebar-item--rankings sidebar-item--your-published-books">Livres publiés</a>
  </div>
</div>

app/views/books/download_book.docx.erb
<h1><%= @book.title %></h1>


<%= render partial: 'download_chapter', collection: @book_content, as: :chapter %>

app/views/books/errors.js.erb
$("#book-errors").empty()
<% @book.errors.full_messages.each do |error| %>
  $("#book-errors").append('<p>' + '<%= error %>' + '</p>')
<% end %>

app/views/books/index.html.erb
<% if @user_library %>
  <!-- User own space -->

  <%= render "books/navbar_dashboard_profile" %>

  <div class="wrapper">

    <%= render "books/sidebar_dashboard" %>

    <div class="content-dashboard content-dashboard--full" id="your-books">
      <%= render "shared/cards" %>
    </div>

    <div class="content-dashboard content-dashboard--full hidden" id="your-published-books">
      <% if @user.has_published? %>
        <%= render "books/card_published_books", books: @books_published %>
      <% else %>
        <p style="text-align: justify">Pour publier un livre, allez dans le chapitre que vous désirez publier et cliquez sur "Publier" (vous devez d'abord créer un livre). </p>
      <% end %>
    </div>

    <div id="modal-container"></div>

  </div>

  <%= render "books/modal_new_book" %>

<% else %>
  <!-- Community books -->

  <%= render "books/navbar_dashboard_community" %>

  <div class="wrapper">

    <%= render "books/sidebar_community" %>

    <% if @books %>

      <div class="content-dashboard content-dashboard--full" id="all-published-books">
          <%= render "books/card_published_books", books: @books %>
          <div id="loader-container" class="hidden">
            <div class="loader" id="loader-1"></div>
          </div>
          <%= render "shared/pagination", filter: @filter %>
      </div>

      <div id="modal-container"></div>

    <% else %>
      <p class="no-book-disclaimer">Pas de livre pour le moment...</p>
    <% end %>

<% end %>

app/views/books/index.js.erb
$(".sidebar-item").removeClass("sidebar-item--active");
$("#sidebar-item--<%= @filter %>").addClass("sidebar-item--active");
$("#all-published-books").html("<%= escape_javascript(render "books/card_published_books", locals: { books: @books } ) %>").append("<%= escape_javascript(render "shared/pagination", locals: { filter: @filter } ) %>");
$('#loader-container').addClass("hidden");

app/views/books/modal_chapters.js.erb
$("#modal-container").html("<%= escape_javascript(render "chapters/modal_published_chapters", locals: { book: @book } ) %>");
$("#publishedChaptersModal").modal();

app/views/books/settings.html.erb
<%= render 'shared/navbar_dashboard', settings: 'settings' %>

<div class="content-dashboard content-dashboard--settings">
  <div class="container container__settings">
    <div class="settings__edit-book">
      <h2 class="text-center">Modifier le livre</h3>
      <%= simple_form_for (@book) do |f| %>
        <%= f.input :title, label: "Titre" %>
        <%= f.input :word_goal, label: "Objectif de mots" %>
        <%= f.button :submit, "Enregistrer" %>
      <% end %>
    </div>
    <a class="btn-inkipit delete-book-button" data-toggle="modal" href="#confirmationDeleteBookModal" data-target="#confirmationDeleteBookModal" id="delete-book-btn">Effacer ce livre</a>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="confirmationDeleteBookModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Etes-vous certain de vouloir effacer <bold><%= @book.title %></bold> ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= link_to 'Oui, je veux effacer ce livre', book_path(@book), method: :delete %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= render "shared/navbar_dashboard", dashboard: 'dashboard' %>

<div class="wrapper">
  <%= render "shared/dashboard_sidebar", chapters: 'chapters' %>
  <div class="content-dashboard content-dashboard--full">
    <%= render "chapters/cards.html.erb" %>
  </div>
</div>

<%= render "chapters/modal_new_chapter" %>

app/views/books/statistics.html.erb
<!-- NAVBAR -->

<%= render 'shared/navbar_dashboard', statistics: 'statistics' %>

<!-- WRAPPER -->

<div class="wrapper">

  <div class="content-dashboard content-dashboard--statistics statistics-grid">

  <div class="sidebar--statistics">
    <div class="sidebar-block wordcount-goal">
      <h2><%= number_with_delimiter(@book.wordcount, delimiter: ' ') %> mots</h2>
      <p>soit <%= number_with_delimiter(@book.signs, delimiter: ' ') %> caractères</p>
      <p>depuis le <%= @book.created_at.strftime('%d/%m/%Y') %></p>
      <% unless @book.word_goal_ratio >= 1 %>
        <canvas id="wordCountGoal"></canvas>
      <% else %>
        <h3 class="gradient-congratulations-text">Objectif atteint !</h3>
        <%= image_tag 'mind_blown.gif', class: "gif" %>
        <div class="underlined-anchor">
          <a class="congratulations-modify-wordcount" href="<%= book_settings_path(@book) %>">Modifier votre objectif de mot ?</a>
        </div>
      <% end %>
    </div>
    <div class="sidebar-footer">
      <div class="sidebar-block">
        <div class="sidebar-block-data">
          <%= @book.chapters.count %>
        </div>
        <div class="sidebar-block-label">
          Chapitres
        </div>
        <div class="sidebar-block-sidenote">
          <%= @words_per_chapter %> mots en moyenne par chapitre
        </div>
      </div>
      <div class="sidebar-horizontal-block hidden-xl-up">
        <div class="sidebar-block">
          <div class="sidebar-block-data">
            <%= @book.characters.count %>
          </div>
          <div class="sidebar-block-label">
            Personnages
          </div>
        </div>
        <div class="sidebar-block">
          <div class="sidebar-block-data">
            <%= @book.places.count %>
          </div>
          <div class="sidebar-block-label">
            Lieux
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- CONTENT -->
    <div class="content-chart content-chart--up">
      <canvas id="wordCounts"></canvas>
    </div>
    <div class="content-chart content-chart--down content-chart--down-1">
      <div class="streaks">
        <div class="streaks-current">
          <div class="streaks-data">
            <div class="icon-circle icon-circle--streak-gold">
              <i class="fa fa-diamond" id="fire-streaks-current" aria-hidden="true"></i>
            </div>
            <%= @book.current_streaks %>
            </div>
          <div class="streaks-text">Actuellement</div>
        </div>
        <div class="streaks-max">
          <div class="streaks-data">
            <div class="icon-circle icon-circle--streak-current">
              <i class="fa fa-diamond" id="fire-streaks-max" aria-hidden="true"></i>
            </div>
            <%= @book.max_streaks %>
            </div>
          <div class="streaks-text">Votre record</div>
        </div>
      </div>
      <div class="content-chart-label">Jours d'écriture consécutifs</div>
    </div>
    <div class="content-chart content-chart--down content-chart--down-2">
      <div class="content-chart-data"><%= @words_per_session %></div>
      <div class="content-chart-label">Mots écrits par jour en moyenne</div>
      <div class="content-chart-data"><%= @global_words_per_session %></div>
      <div class="content-chart-label">Moyenne des autres auteurs</div>
    </div>
    <div class="content-chart content-chart--down content-chart--down-3">
      <div id="cal-heatmap"></div>
      <div class="content-chart-label hidden-sm hidden-md">Calendrier de vos contributions</div>
    </div>
  </div>

</div>

<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/fr.js"></script>


<% content_for(:after_js) do %>
  <%= javascript_include_tag 'statistics_manifest'%>
<% end %>