config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticated :user do
    root 'books#index', as: :authenticated_root, "user_id"=>true
  end

  root to: 'pages#landing'

  resources :users, only: [:show, :update] do
    resources :books, only: [:index], name_prefix: "user_"
  end

  resources :books, only: [:show, :new, :create, :update, :destroy] do
    resources :chapters, only: [:create, :show, :update, :destroy], name_prefix: "book_"
    resources :characters, only: [:create, :index, :show, :update, :destroy], name_prefix: "book_"
    resources :places, only: [:create, :index, :show, :destroy], name_prefix: "book_"
  end

  resources :users, only: :show

  resources :books, only: :index

  resources :relationships, only: [:create, :destroy]

  resources :reactions, only: [:create, :update]

  get "modal_chapters" => 'books#modal_chapters', as: 'modal_chapters'

  get "books" => "books#index",  as: :user_root_path

  get "books/:book_id/statistics" => "books#statistics", as: :book_statistics

  get "books/:book_id/settings" => "books#settings", as: :book_settings

  get "books/:book_id/chapters/:chapter_id/refresh_wordcount" => "chapters#refresh_wordcount", as: :refresh_wordcount

  get "books/:book_id/download" => "books#download", as: :download_book, format: 'docx'

  get "/rankings" => "pages#rankings", as: :rankings

  get "/privacy" => "pages#privacy_policy"

  get "/tos" => "pages#tos"

  get "/cgu" => "pages#cgu", as: :cgu

  get "/mentions_legales" => "pages#mentions_legales", as: :mentions_legales

  mount Attachinary::Engine => "/attachinary"

end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :book
  has_many :appearances
  has_many :chapters, through: :appearances
  has_many :characters, through: :appearances

  delegate :user, :to => :book, :allow_nil => true
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def create
    @place = Place.new(place_params)
    @place.book = Book.find(params[:book_id])
    authorize @place

    if @place.save
      redirect_to book_places_path(@place.book), alert: "Vous avez ajouté un nouveau lieu!"
    end
  end

  def index
    @book = Book.find(params[:book_id])
    @places = policy_scope(Place).where(book: @book)

    @place = Place.new
    @characters = @book.characters
    @chapters = @book.chapters
  end

  def destroy
    book = Book.find(params[:book_id])
    @place = Place.find(params[:id])
    authorize @place

    @place.destroy

    redirect_to book_places_path(book)
  end

  private

  def place_params
    params.require(:place).permit(:name)
  end
end

app/views/places/_cards.html.erb
<div class="card card--add card--place" id="add-place-card">
  <div class="card__upper-content">
    <div class="card__title-section card__title--add" id="text-add-a-chapter">Ajouter un lieu</div>
    <i class="fa fa-plus-square-o" id="plus-add-a-chapter" aria-hidden="true"></i>
  </div>
  <a class="card__link card__link--add" data-toggle="modal" href="#exampleModal" data-target="#exampleModal" id="add-place-btn"></a>
</div>

<% @places.each do |place| %>

    <div class="card card--chapter">
      <%= link_to "", book_place_path(@book, place), method: :delete, class: "fa fa-trash", data: { confirm: "Etes-vous certain de vouloir effacer ce lieu ?" } %>
      <div class="card__upper-content">
        <div class="card__title-section">
          <h3 class="card__title"><%= truncate(place.name, length: 50, separator: ' ')  %></h3>
        </div>
      </div>
      <div class="card__lower-content">
      </div>
      <%= link_to "", book_places_path(@book), class:"card__link" %>
   </div>

<% end %>

app/views/places/index.html.erb
<%= render "shared/navbar_dashboard", dashboard: 'dashboard' %>

<div class="wrapper">
  <%= render "shared/dashboard_sidebar", places: 'places' %>
  <div class="content-dashboard content-dashboard--full">
    <%= render "places/cards.html.erb" %>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="newPlace" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ajouter un nouveau lieu</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@book, @place] do |f| %>
          <%= f.input :name, label: 'Nom', placeholder: 'Poudlard' %>
      </div>
      <p class="disclaimer">Cette fonctionnalité est en cours de développement. Vous pouvez ajouter un lieu, mais pas encore accéder à sa fiche détaillée.</p>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
        <%= f.button :submit, "Ajouter ce lieu", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>